theme: "tale-hugo"
baseURL: https://anneliesq.github.io/Gov1347-Blog/
languageCode: en-us
title: My New Hugo Site
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
markup:
  goldmark:
    renderer:
      unsafe: true
