---
title: "A Terrible District Level Forecast"
author: "Yao Yu"
date: "9/29/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Loading in necessary libraries
library(tidyverse)
library(janitor)

# Reading in the data
expert_ratings <- read_csv("expert_rating.csv")
historical_results <- read_csv("house party vote share by district 1948 to 2020.csv") %>% 
  clean_names()
```

```{r cleaning the data}
# Selecting columns
avg_ratings <- expert_ratings %>% 
<<<<<<< HEAD
  rename("district_num" = "district") %>% 
  select(year, state, district_num, avg_rating)

dem_results <- historical_results %>% 
  select(raceYear, State, Area, DemVotesMajorPercent) %>% 
  rename("year" = "raceYear") %>% 
  rename("state" = "State") %>% 
  rename("area" = "Area") %>% 
  separate(area, into = c("area", "district_num"), sep = " ") %>% 
  select(-area) %>% 
  mutate(district_num = case_when(
    district_num == "Large" ~ "AL",
    TRUE ~ district_num
=======
  select(year, state, district, avg_rating)

dem_results <- historical_results %>% 
  select(race_year, state, area, dem_votes_major_percent) %>% 
  rename("year" = "race_year") %>% 
  separate(area, into = c("area", "district"), sep = " ") %>% 
  select(-area) %>% 
  mutate(district = case_when(
    district == "Large" ~ "AL",
    TRUE ~ district
>>>>>>> e3b5af643577257506a9596339695707b0aaf77e
  ))

# Joining the data and nesting by state and district
train_data <- avg_ratings %>% 
  filter(year != 2022) %>% 
  # left join as there aren't ratings for every district
<<<<<<< HEAD
  left_join(dem_results, by = c("year", "state", "district_num")) %>% 
  group_by(state, district_num) %>% 
=======
  left_join(dem_results, by = c("year", "state", "district")) %>% 
  group_by(state, district) %>% 
>>>>>>> e3b5af643577257506a9596339695707b0aaf77e
  filter(n() > 1) %>% # Filtering out single data rows
  group_nest() %>% 
  mutate(data = map(data, ~unnest(., cols = c())))

test_data <- avg_ratings %>% 
  filter(year == 2022) %>% 
<<<<<<< HEAD
  left_join(dem_results, by = c("year", "state", "district_num")) %>%
  group_by(state, district_num) %>% 
=======
  group_by(state, district) %>% 
>>>>>>> e3b5af643577257506a9596339695707b0aaf77e
  group_nest() %>% 
  mutate(data = map(data, ~unnest(., cols = c())))
```

```{r models}
# Building TERRIBLE models
models <- train_data %>% 
<<<<<<< HEAD
  mutate(model = map(data, ~lm(DemVotesMajorPercent ~ avg_rating, # this is where you add your other variables
=======
  mutate(model = map(data, ~lm(dem_votes_major_percent ~ avg_rating + ____ + _____, # this is where you add your other variables
>>>>>>> e3b5af643577257506a9596339695707b0aaf77e
                                  data = .x))) %>%  
  select(-data)

# map creates a model on each district
# creates lm for each ^

# Extracting TERRIBLE model results
model_results <- models %>% 
  mutate(r_squared = map_dbl(model, ~summary(.x)$r.squared))
#prints r.squared and adjusted r.squared
<<<<<<< HEAD
is.vector(models$model)
# Predicting 2022 with a TERRIBLE model
pred_2022 <- test_data %>%
  # inner join as there may not be historical models for some districts
  inner_join(models, by = c("state", "district_num")) %>% 
=======

# Predicting 2022 with a TERRIBLE model
pred_2022 <- test_data %>%
  
  # inner join as there may not be historical models for some districts
  inner_join(models, by = c("state", "district")) %>% 
>>>>>>> e3b5af643577257506a9596339695707b0aaf77e
  mutate(pred = map_dbl(.x = model, .y = data, ~predict(object = .x, newdata = as.data.frame(.y)))) %>%
  select(state, district, pred)
```

